compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: ubuntu-os-cloud
  image_name: ubuntu-2204-jammy-arm64-v20220712a
  cpu: 8
  memory: 32G
  disk: 300
env:
  GITHUB_TOKEN: ENCRYPTED[!34f230443710315e76a14b50330a58b7367fad944be1c1d3e6ac8e0bc4c5266fcd04d3254757de8a10eef6739e0a1fe4!]

