compute_engine_instance:
  image_project: cirrus-images # GCP project.
  image: family/docker-kvm # family or a full image name.
  platform: linux
  architecture: amd64 # optional. By default, amd64 is assumed.
  cpu: 8 # optional. Defaults to 2 CPUs.
  memory: 16G # optional. Defaults to 4G.
  disk: 256 # optional. By default, uses the smallest disk size required by the image.
  nested_virtualization: true
env:
  GITHUB_TOKEN: ENCRYPTED[!34f230443710315e76a14b50330a58b7367fad944be1c1d3e6ac8e0bc4c5266fcd04d3254757de8a10eef6739e0a1fe4!]

task:

  
  setup_script: |
    gg
    
